### ISSUE TITLE
ISIS Project public API

### ISSUE THREAD

**Issue by rbeyer** [planetarysoftware/ISIS_TC#145]
We are having a good discussion in #140 about what constitutes a "breaking change."

Based on conversations in our TC meetings, we really wanted to try and have better written guidelines for what constitutes a breaking change in our codebase that would trigger a major version increment.  As we have all agreed, since the ISIS project is following Semantic Versioning, a "breaking change" is defined as a "backwards incompatible change introduced to the public API."  The difficultly, perhaps, is that we have not yet formally defined and agreed upon what the ISIS public API *is*, as required by the first element of the SemVer Specfication.

Such a definition is therefore a necessary first step before we should even be having a discussion about what constitutes a "breaking change" and then once we do, we still have to figure out how to deal with them from a policy and workforce standpoint (which is its own can of worms), but first things first:

# Proposed definition of the "ISIS Project public API"

The public API is considered to be all the interfaces that the ISIS project provides to the community from which the ISIS user base can build more complex tools.  This API therefore includes code-level structures accessible via software calls to libraries, but also more user-facing structures like command-line programs and graphical user interface (GUI) programs.  Any "interface" via which a user can reasonably interact with components of the ISIS project should be considered part of the "ISIS Project public API" for the purposes of Semantic Versioning.

Examples are provided below, but are not meant to be exhaustive or complete.  The above philosophy should guide our thinking in what the public API is.

**Code-level structures**: Function, class, and object names, argument signatures, and return signatures for functions, classes, and objects.

- C++ code exceptions would be those structures above marked with a "private" access specifier via the C++ language.
- Python code exceptions would be those structures above which do not begin with an underbar ("_", as per Python language tradition).

**User-facing command-line and GUI programs**: program name, argument list, argument defaults, configuration or preference names and their defaults, and output file structure and contents.

**Comment by jessemapel** [comment]
I totally agree with everything but this part

> output file structure and contents.

This is too nebulous to be helpful. I would take a more file-type by file-type approach.

1. For anything of an inherently unstructured file-type, like .txt; we make no guarnatee of its contents; just that it will exist.
2. For CSV files; column names and data types are a part of the API. For example, the "minimum" column will exist and it will contain floating point numbers or possibly the word "NULL".
3. For PVL files; object, group, and keyword names are a part of the API. For example, the "minimum" keyword will exist in the "statistics" group. This also applies to Cube files. I do not think we can guarantee any value types here as PVL is entirely string based.
4. For binary control network files; all versions of the software within the same major version will be able to ingest them. We do not guarantee the PVL headers in these. The protobuf specs basically define the binary data structure here but I'm not sure if that should be a part of the API.

I would also note that new CSV column headers or new PVL keywords can be added without breaking the API. So, checking that something does not exist is not a "safe" operation.

**Comment by rbeyer** [comment]
My intent was to keep this "definition" general, so that it could be interpreted and applied in many circumstances, but I agree with @jessemapel: as is, it is too vague to be useful.

Based on their examples, I think I would change my last sentence from ending:

> ... defaults, and output file structure and contents.

to

>  ... defaults, and for those programs with structured output files, the
structure and contents of those output files are analogous to the return signatures
of code-level structures.

The intent here being that just as there are complicated considerations that apply to what changes a function "return signature" based on return type and value, there are similarly complex considerations that must be considered for output files, depending on their file type and contents.  There could certainly be better wording here.  Whatever words we use, I think they should support the specific examples @jessemapel illuminates.

Below that kind of top-level paragraph and the two general example categories of **Code-level structures** and **User-facing command-line and GUI programs** if we want to dive into specifics, and detail rules for this output type or that output type, we certainly can, but perhaps we should leave that to a PR-Review-Accept cycle on a policy document that starts with the above definition, if we can at least agree on that?

**Comment by jessemapel** [comment]
@rbeyer I think that moving to a PR to refine the wording is a good idea.

**Comment by KrisBecker** [comment]
A significant amount of ISIS code is developed as a plugin type interface. Most, if not all of these implementations are behind a public facing generic or abstract class APIs. This includes camera models, map projections, photometric functions, databases (drivers), shape model interfaces and others. There are currently more than 100 of these types of plugin implementations. Direct instantiation of any of these implementations is rare if ever done except through plugin factories. 

We have been discussing if output file content is part of the ISIS API for purposes of defining breaking changes for purposes of conditions for semantic versioning. It appears that that we are coming to consensus that some conditions in output files are part of the ISIS API and do impact major versioning. How do changes in these plugin-driven implementations affect ISIS versioning? Does this same situation apply/extend to cube images and/or labels (structure or content) that are changed/modified in ISIS?

Camera models make up the majority of plugin implementations in ISIS and are likely the biggest source of changes seen in images. The Camera class serves as the generic public facing API for all individual instrument camera models. There are many things within the entire Camera framework that can affect/alter the resulting image. For example, simply adding or changing a camera distortion model, or a simple bug fix may change geometry data. In fact, changes to SPICE kernels have a similar effect. Suppose you modify the IAK ITRANS/TRANS mapping that changes the axis orientation of the image that is required in order for noproj to produce the correct orientation of the undistorted image. This is not hypothetical as it does and has occurred. We have seen this with the OREX SamCam and Rosetta OSIRIS NAC/WAC camera models. Solutions range from IAK changes to flipping and/or mirroring the image on import by instrument specific ISIS ingestion applications (e.g., rososiris2isis).

Note that camera models have their own versioning system that is actually enforced at runtime. How does the camera model versioning mechanism indicating breaking changes within images coexist and impact ISIS semantic versioning?

**Comment by jessemapel** [comment]
The plugins are challenging because there are multiple plugin systems that work in different ways. In general, I would say that the interfaces the Plugins use is part of the API but the actual implementations that you load are now. So, Camera is part of the API, LroNarrowAngleCamera is not.

**Comment by KrisBecker** [comment]
So by that distinction, if the CSV file was changed in/by a plugin, it would not be subject to semantic versioning?

**Comment by jessemapel** [comment]
If the values in the CSV were modified by a change in a plugin I think that's fine. If changing a plugin changes the name of a column that would be a problem (I would also be VERY dubious of the code that generates the CSV).
